### ISSUE TITLE
Nested ingredients lists 

### ISSUE THREAD

**Issue by binnev** [binnev/recipes#1]
Support nested ingredient lists in the yaml:

```yaml
ingredients:
- spice mix 1:
	- cumin
	- coriander
- spice mix 2:
	- turmeric
	- cumin
- chicken
- rice
```
